/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillageRouteImport } from './routes/village'
import { Route as ShgDashboardRouteImport } from './routes/shg-dashboard'
import { Route as ShgRouteImport } from './routes/shg'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MemberTalpatRouteImport } from './routes/member-talpat'
import { Route as MemberHistoryRouteImport } from './routes/member-history'
import { Route as MemberRouteImport } from './routes/member'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GramPanchayatRouteImport } from './routes/gram-panchayat'
import { Route as IndexRouteImport } from './routes/index'

const VillageRoute = VillageRouteImport.update({
  id: '/village',
  path: '/village',
  getParentRoute: () => rootRouteImport,
} as any)
const ShgDashboardRoute = ShgDashboardRouteImport.update({
  id: '/shg-dashboard',
  path: '/shg-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ShgRoute = ShgRouteImport.update({
  id: '/shg',
  path: '/shg',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberTalpatRoute = MemberTalpatRouteImport.update({
  id: '/member-talpat',
  path: '/member-talpat',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberHistoryRoute = MemberHistoryRouteImport.update({
  id: '/member-history',
  path: '/member-history',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GramPanchayatRoute = GramPanchayatRouteImport.update({
  id: '/gram-panchayat',
  path: '/gram-panchayat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gram-panchayat': typeof GramPanchayatRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/member-history': typeof MemberHistoryRoute
  '/member-talpat': typeof MemberTalpatRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/shg': typeof ShgRoute
  '/shg-dashboard': typeof ShgDashboardRoute
  '/village': typeof VillageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gram-panchayat': typeof GramPanchayatRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/member-history': typeof MemberHistoryRoute
  '/member-talpat': typeof MemberTalpatRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/shg': typeof ShgRoute
  '/shg-dashboard': typeof ShgDashboardRoute
  '/village': typeof VillageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gram-panchayat': typeof GramPanchayatRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/member-history': typeof MemberHistoryRoute
  '/member-talpat': typeof MemberTalpatRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/shg': typeof ShgRoute
  '/shg-dashboard': typeof ShgDashboardRoute
  '/village': typeof VillageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gram-panchayat'
    | '/login'
    | '/member'
    | '/member-history'
    | '/member-talpat'
    | '/register'
    | '/reports'
    | '/shg'
    | '/shg-dashboard'
    | '/village'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gram-panchayat'
    | '/login'
    | '/member'
    | '/member-history'
    | '/member-talpat'
    | '/register'
    | '/reports'
    | '/shg'
    | '/shg-dashboard'
    | '/village'
  id:
    | '__root__'
    | '/'
    | '/gram-panchayat'
    | '/login'
    | '/member'
    | '/member-history'
    | '/member-talpat'
    | '/register'
    | '/reports'
    | '/shg'
    | '/shg-dashboard'
    | '/village'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GramPanchayatRoute: typeof GramPanchayatRoute
  LoginRoute: typeof LoginRoute
  MemberRoute: typeof MemberRoute
  MemberHistoryRoute: typeof MemberHistoryRoute
  MemberTalpatRoute: typeof MemberTalpatRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ShgRoute: typeof ShgRoute
  ShgDashboardRoute: typeof ShgDashboardRoute
  VillageRoute: typeof VillageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/village': {
      id: '/village'
      path: '/village'
      fullPath: '/village'
      preLoaderRoute: typeof VillageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shg-dashboard': {
      id: '/shg-dashboard'
      path: '/shg-dashboard'
      fullPath: '/shg-dashboard'
      preLoaderRoute: typeof ShgDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shg': {
      id: '/shg'
      path: '/shg'
      fullPath: '/shg'
      preLoaderRoute: typeof ShgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-talpat': {
      id: '/member-talpat'
      path: '/member-talpat'
      fullPath: '/member-talpat'
      preLoaderRoute: typeof MemberTalpatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-history': {
      id: '/member-history'
      path: '/member-history'
      fullPath: '/member-history'
      preLoaderRoute: typeof MemberHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gram-panchayat': {
      id: '/gram-panchayat'
      path: '/gram-panchayat'
      fullPath: '/gram-panchayat'
      preLoaderRoute: typeof GramPanchayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GramPanchayatRoute: GramPanchayatRoute,
  LoginRoute: LoginRoute,
  MemberRoute: MemberRoute,
  MemberHistoryRoute: MemberHistoryRoute,
  MemberTalpatRoute: MemberTalpatRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ShgRoute: ShgRoute,
  ShgDashboardRoute: ShgDashboardRoute,
  VillageRoute: VillageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
